cc_binary (
  name = "delete_chars_tobe_palindrome",
  srcs = [
    "delete_chars_tobe_palindrome.cc",
  ],
)

cc_binary (
  name = "split_odd_even",
  srcs = [
    "split_odd_even.cc",
  ],
)

cc_binary (
  name = "golden_flower",
  srcs = [
    "golden_flower.cc",
  ],
)

cc_binary (
  name = "add_one_char_tobe_palindrome",
  srcs = [
    "add_one_char_tobe_palindrome.cc",
  ],
)
