cc_binary (
  name = "kmp",
  srcs = [
    "kmp.cc",
  ],
)

cc_binary (
  name = "delete_chars_tobe_palindrome",
  srcs = [
    "delete_chars_tobe_palindrome.cc",
  ],
)

cc_binary (
  name = "split_odd_even",
  srcs = [
    "split_odd_even.cc",
  ],
)

cc_binary (
  name = "golden_flower",
  srcs = [
    "golden_flower.cc",
  ],
)

cc_binary (
  name = "add_one_char_tobe_palindrome",
  srcs = [
    "add_one_char_tobe_palindrome.cc",
  ],
)

cc_binary (
  name = "deduplicate_chars",
  srcs = [
    "deduplicate_chars.cc",
  ],
)

cc_binary (
  name = "path_of_sum",
  srcs = [
    "path_of_sum.cc",
  ],
)

cc_binary (
  name = "max_average",
  srcs = [
    "max_average.cc",
  ],
)

cc_binary (
  name = "shortest_summary",
  srcs = [
    "shortest_summary.cc",
  ],
)

cc_binary (
  name = "red_packet",
  srcs = [
    "red_packet.cc",
  ],
)

cc_binary (
  name = "climb_stairs",
  srcs = [
    "climb_stairs.cc",
  ],
)

cc_binary (
  name = "bonus",
  srcs = [
    "bonus.cc",
  ],
)

cc_binary (
  name = "min_subsequence",
  srcs = [
    "min_subsequence.cc",
  ],
)
