cc_binary (
  name = "lintcode_2_Trailing_Zeros",
  srcs = [
    "2_Trailing_Zeros.cc",
  ]
)

cc_binary (
  name = "lintcode_40_Implement_Queue_by_Two_Stacks",
  srcs = [
    "40_Implement_Queue_by_Two_Stacks.cc",
  ]
)

cc_binary (
  name = "lintcode_41_Maximum_Subarray",
  srcs = [
    "41_Maximum_Subarray.cc",
  ]
)

cc_binary (
  name = "lintcode_70_Binary_Tree_Level_Order_Traversal_II",
  srcs = [
    "70_Binary_Tree_Level_Order_Traversal_II.cc",
  ]
)

cc_binary (
  name = "lintcode_78_Longest_Common_Prefix",
  srcs = [
    "78_Longest_Common_Prefix.cc",
  ]
)

cc_binary (
  name = "lintcode_99_Reorder_List",
  srcs = [
    "99_Reorder_List.cc",
  ],
)

cc_binary (
  name = "lintcode_100_Remove_Duplicates_from_Sorted_Array",
  srcs = [
    "100_Remove_Duplicates_from_Sorted_Array.cc",
  ],
)

#cc_binary (
#  name = "lintcode_132_Word_Search_II",
#  srcs = [
#    "132_Word_Search_II.cc",
#  ]
#)

cc_binary (
  name = "lintcode_423_Valid_Parentheses",
  srcs = [
    "423_Valid_Parentheses.cc",
  ],
)
