cc_binary (
  name = "lintcode_2_Trailing_Zeros",
  srcs = [
    "2_Trailing_Zeros.cc",
  ]
)

cc_binary (
  name = "lintcode_40_Implement_Queue_by_Two_Stacks",
  srcs = [
    "40_Implement_Queue_by_Two_Stacks.cc",
  ]
)

cc_binary (
  name = "lintcode_41_Maximum_Subarray",
  srcs = [
    "41_Maximum_Subarray.cc",
  ]
)

cc_binary (
  name = "lintcode_51_Previous_Permutation",
  srcs = [
    "51_Previous_Permutation.cc",
  ],
)

cc_binary (
  name = "lintcode_52_Next_Permutation",
  srcs = [
    "52_Next_Permutation.cc",
  ],
)

cc_binary (
  name = "lintcode_53_Reverse_Words_in_a_String",
  srcs = [
    "53_Reverse_Words_in_a_String.cc",
  ],
)

cc_binary (
  name = "lintcode_55_Compare_Strings",
  srcs = [
    "55_Compare_Strings.cc",
  ],
)

cc_binary (
  name = "lintcode_70_Binary_Tree_Level_Order_Traversal_II",
  srcs = [
    "70_Binary_Tree_Level_Order_Traversal_II.cc",
  ]
)

cc_binary (
  name = "lintcode_78_Longest_Common_Prefix",
  srcs = [
    "78_Longest_Common_Prefix.cc",
  ]
)

cc_binary (
  name = "lintcode_80_Median",
  srcs = [
    "80_Median.cc",
  ],
)

cc_binary (
  name = "lintcode_81_Data_Stream_Median",
  srcs = [
    "81_Data_Stream_Median.cc",
  ],
)

cc_binary (
  name = "lintcode_82_Single_Number",
  srcs = [
    "82_Single_Number.cc",
  ],
)

cc_binary (
  name = "lintcode_83_Single_Number_II",
  srcs = [
    "83_Single_Number_II.cc",
  ],
)

cc_binary (
  name = "lintcode_84_Single_Number_III",
  srcs = [
    "84_Single_Number_III.cc",
  ],
)

cc_binary (
  name = "lintcode_96_Partition_List",
  srcs = [
    "96_Partition_List.cc",
  ],
)

cc_binary (
  name = "lintcode_98_Sort_List",
  srcs = [
    "98_Sort_List.cc",
  ],
)

cc_binary (
  name = "lintcode_99_Reorder_List",
  srcs = [
    "99_Reorder_List.cc",
  ],
)

cc_binary (
  name = "lintcode_100_Remove_Duplicates_from_Sorted_Array",
  srcs = [
    "100_Remove_Duplicates_from_Sorted_Array.cc",
  ],
)

#cc_binary (
#  name = "lintcode_132_Word_Search_II",
#  srcs = [
#    "132_Word_Search_II.cc",
#  ]
#)

cc_binary (
  name = "lintcode_136_Palindrome_Partitioning",
  srcs = [
    "136_Palindrome_Partitioning.cc",
  ],
)

cc_binary (
  name = "lintcode_423_Valid_Parentheses",
  srcs = [
    "423_Valid_Parentheses.cc",
  ],
)

cc_binary (
  name = "lintcode_491_Palindrome_Number",
  srcs = [
    "491_Palindrome_Number.cc",
  ],
)

cc_binary (
  name = "lintcode_678_Convert_Palindrome",
  srcs = [
    "678_Convert_Palindrome.cc",
  ],
)
