
cc_binary (
  name = "leetcode_21_Merge_Two_Sorted_Lists",
  srcs = [
    "21_Merge_Two_Sorted_Lists.cc",
  ]
)

cc_binary (
  name = "leetcode_28_Remove_Duplicates_from_Sorted_Array",
  srcs = [
    "28_Remove_Duplicates_from_Sorted_Array.cc",
  ],
)

cc_binary (
  name = "leetcode_136_Single_Number",
  srcs = [
    "136_Single_Number.cc",
  ],
)

cc_binary (
  name = "leetcode_137_Single_Number_II",
  srcs = [
    "137_Single_Number_II.cc",
  ],
)
