cc_binary (
  name = "leetcode_136_Single_Number",
  srcs = [
    "136_Single_Number.cc",
  ],
)

cc_binary (
  name = "leetcode_137_Single_Number_II",
  srcs = [
    "137_Single_Number_II.cc",
  ],
)
